title: "SILITUZ"
url: "https://silituz.de"
baseurl: ""          # leer bei Root-Domain
theme: null          # eigenes Layout
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

# Navigation aus _data/nav.yml
defaults:
  - scope: { path: "" }
    values:
      layout: default
