title: "SILITUZ"
description: "Silituz – KI • Musik • Anime."
# GitHub Pages rendert Jekyll automatisch – keine weiteren Einstellungen nötig.
# Wenn du irgendwann Unterordner nutzt, kannst du baseurl setzen.

