# saubere, sprechende URLs
permalink: pretty

# Standard-Sprache = Deutsch
lang: de

# Defaults für Sprachen über Ordner
defaults:
  # alles (Standard: de)
  - scope:
      path: ""
    values:
      lang: de
  # alles unter /en/ ist Englisch
  - scope:
      path: "en"
    values:
      lang: en
